### ISSUE TITLE
Access to Dataset

### ISSUE THREAD

**Issue by radaimi** [ParitoshParmar/Piano-Skills-Assessment#1]
Hi, I've submitted a request access to the dataset but have not heard back. Is it possible to get access? I'm a PhD student and would like to use the dataset for research purposes. Thank you!

**Comment by ParitoshParmar** [comment]
Hi @radaimi: Sorry about that. I just updated the link to the dataset. Can you please try downloading it again?

**Comment by radaimi** [comment]
Thank you, i was able to download the data!
